<?php
include_once 'vfsStream/vfsStream.php';
/**
 * Test class for Dfp_Datafeed_Transfer
 * Generated by PHPUnit on 2011-12-09 at 10:59:43.
 *
 */
class Dfp_Datafeed_TransferTest extends PHPUnit_Framework_TestCase
{
    public function testSendFile()
    {
        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');

        $mockAdapter->expects($this->once())->method('sendFile')
                    ->with($this->equalTo('test.txt'), $this->equalTo('test.csv'));

        $sut = new Dfp_Datafeed_Transfer();
        $sut->setAdapter($mockAdapter);

        $sut->sendFile('test.txt', 'test.csv');
    }

    public function testRetrieveFile()
    {
        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');

        $mockAdapter->expects($this->once())->method('retrieveFile')
                    ->with($this->equalTo('test.txt'), $this->equalTo('test.csv'));

        $sut = new Dfp_Datafeed_Transfer();
        $sut->setAdapter($mockAdapter);

        $sut->retrieveFile('test.txt', 'test.csv');
    }

    public function testSendFiles()
    {
        $sut = $this->getMock('Dfp_Datafeed_Transfer', array('sendFile'));
        $sut->expects($this->at(0))->method('sendFile')->with($this->equalTo('test.txt'), $this->equalTo('test.txt'));
        $sut->expects($this->at(1))->method('sendFile')
            ->with($this->equalTo('file.gif'), $this->equalTo('images/file.gif'));

        $sut->sendFiles(array('test.txt','file.gif'), array('test.txt', 'images/file.gif'));
    }

    public function testRetrieveFiles()
    {
        $sut = $this->getMock('Dfp_Datafeed_Transfer', array('retrieveFile'));
        $sut->expects($this->at(0))->method('retrieveFile')
            ->with($this->equalTo('test.txt'), $this->equalTo('test.txt'));
        $sut->expects($this->at(1))->method('retrieveFile')
            ->with($this->equalTo('file.gif'), $this->equalTo('images/file.gif'));

        $sut->retrieveFiles(array('test.txt','file.gif'), array('test.txt', 'images/file.gif'));
    }

    public function testGetAdapter()
    {
        $sut = new Dfp_Datafeed_Transfer();
        try {
            $sut->getAdapter();
        } catch (Dfp_Datafeed_Transfer_Exception $e) {
        	$this->assertEquals($e->getMessage(), 'Invalid Adapter Specified');
        	return;
        }

        $this->fail('Exception not thrown');
    }

    public function testSetAdapterString()
    {
        $name = 'test' . uniqid();
        $className = 'Dfp_Datafeed_Transfer_Adapter_' . ucfirst($name);

        $sut = new Dfp_Datafeed_Transfer();
        $mockAdapter = $this->getMock(
        	'Dfp_Datafeed_Transfer_Adapter_Interface',
        	array(),
        	array(),
        	$className
        );

        $sut->setAdapterString($name);

        $this->assertInstanceOf($className, $sut->getAdapter());
    }

    public function testGetAdapterNamespace()
    {
        $sut = new Dfp_Datafeed_Transfer();

        $this->assertEquals('Dfp_Datafeed_Transfer_Adapter', $sut->getAdapterNamespace());
    }

    public function testSetAdapterNamespace()
    {
        $sut = new Dfp_Datafeed_Transfer();

        $sut->setAdapterNamespace('test');

        $this->assertEquals('test', $sut->getAdapterNamespace());
    }

    public function testSetAdapter()
    {
        $sut = new Dfp_Datafeed_Transfer();
        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');

        $sut->setAdapter($mockAdapter);

        $this->assertSame($mockAdapter, $sut->getAdapter());
    }

    public function testSetConfig()
    {
        $options = array('adapterNamespace'=>'Test_Namespace');

        $config = new Zend_Config($options);

        $sut = $this->getMock('Dfp_Datafeed_Transfer', array('setOptions'));
        $sut->expects($this->once())->method('setOptions')->with($this->equalTo($options));

        $sut->setConfig($config);
    }

    public function testSetOptions()
    {
        $options = array('adapter'=>'ftp','adapterOption'=>'value','adapterNamespace'=>'Test_Namespace');

        $sut = $this->getMock('Dfp_Datafeed_Transfer', array('getAdapter','setAdapterString', 'setAdapterNamespace'));

        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');
        $mockAdapter->expects($this->once())->method('setOptions')
                    ->with($this->equalTo(array('adapterOption'=>'value')));
        $sut->expects($this->any())->method('getAdapter')->will($this->returnValue($mockAdapter));

        $sut->expects($this->once())->method('setAdapterString')->with($this->equalTo('ftp'));
        $sut->expects($this->once())->method('setAdapterNamespace')->with($this->equalTo('Test_Namespace'));

        $sut->setOptions($options);

        //test with a adapter instance

        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');
        $options = array('adapter'=>$mockAdapter);

        $sut = new Dfp_Datafeed_Transfer();
        $sut->setOptions($options);

        $this->assertEquals($mockAdapter, $sut->getAdapter());

        //test with invalid adapter

        $passed = false;
        $sut = new Dfp_Datafeed_Transfer();
        $options = array('adapter'=>array());
        try {
            $sut->setOptions($options);
        } catch (Dfp_Datafeed_Transfer_Exception $e) {
            if ($e->getMessage() == 'Invalid adapter specified') {
                $passed = true;
            }
        }
        $this->assertTrue($passed, 'Adapter exception not thrown');

        $sut = new Dfp_Datafeed_Transfer();
        $options = array('adapterNamespace'=>array());
        try {
            $sut->setOptions($options);
        } catch (Dfp_Datafeed_Transfer_Exception $e) {
            if ($e->getMessage() == 'Invalid adapter namespace specified') {
                return;
            }
        }

        $this->fail('Adapter namespace exception not thrown');
    }

    public function test__construct()
    {
        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');
        $options = array('adapter'=>$mockAdapter);

        $sut = new Dfp_Datafeed_Transfer($options);

        $this->assertEquals($mockAdapter, $sut->getAdapter());
        $c = new Zend_Config($options);

        $sut = new Dfp_Datafeed_Transfer($c);

        $this->assertEquals($mockAdapter, $sut->getAdapter());

        try {
            $sut = new Dfp_Datafeed_Transfer('invalid');
        } catch (Dfp_Datafeed_Transfer_Exception $e) {
            if ($e->getMessage() == 'Invalid parameter to constructor') {
                return;
            }
        }

        $this->fail('Exception not thrown');
    }

    public function testAddError()
    {
        $sut = new Dfp_Datafeed_Transfer();
        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');
        $mockAdapter->expects($this->once())->method('addError')->with($this->equalTo('error'));

        $sut->setAdapter($mockAdapter);

        $sut->addError('error');
    }

    public function testAddErrors()
    {
        $sut = new Dfp_Datafeed_Transfer();
        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');
        $mockAdapter->expects($this->once())->method('addErrors')->with($this->equalTo(array('error','error2')));

        $sut->setAdapter($mockAdapter);

        $sut->addErrors(array('error','error2'));
    }

    public function testGetErrors()
    {
        $sut = new Dfp_Datafeed_Transfer();
        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');
        $mockAdapter->expects($this->once())->method('getErrors')->will($this->returnValue(array('error')));

        $sut->setAdapter($mockAdapter);

        $this->assertEquals(array('error'), $sut->getErrors());
    }

    public function testHasErrors()
    {
        $sut = new Dfp_Datafeed_Transfer();
        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');
        $mockAdapter->expects($this->once())->method('hasErrors')->will($this->returnValue(true));

        $sut->setAdapter($mockAdapter);

        $this->assertEquals(true, $sut->hasErrors());
    }

    public function testSetErrors()
    {
        $sut = new Dfp_Datafeed_Transfer();
        $mockAdapter = $this->getMock('Dfp_Datafeed_Transfer_Adapter_Interface');
        $mockAdapter->expects($this->once())->method('setErrors')->with($this->equalTo(array('error','error2')));

        $sut->setAdapter($mockAdapter);

        $sut->setErrors(array('error','error2'));
    }

}
